[package]
name = "pysephwasntavailable/packetprofiler"
version = "1.4.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Remote packet profiler"
license = "MIT"

[dependencies]
Roact = "pysephwasntavailable/roact-constant-fork@1.5.0"
PacketSizeCounter = "pysephwasntavailable/remotepacketsizecounter@2.4.1"
Signal = "stravant/goodsignal@0.2.1"